// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEsr-_PQnPL3Z2QNqGncizFb_XeRXl7SI',
    appId: '1:129633734813:android:8d9162789cfbd5ea82c474',
    messagingSenderId: '129633734813',
    projectId: 'flutter-starter-49185',
    storageBucket: 'flutter-starter-49185.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq8MmhkjzDsYa6t-aqM-gQ8yHpLVx71TI',
    appId: '1:129633734813:ios:8aa52932d164ab1782c474',
    messagingSenderId: '129633734813',
    projectId: 'flutter-starter-49185',
    storageBucket: 'flutter-starter-49185.appspot.com',
    iosBundleId: 'com.example.firebaseexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq8MmhkjzDsYa6t-aqM-gQ8yHpLVx71TI',
    appId: '1:129633734813:ios:4d1d5e6429ef2dd782c474',
    messagingSenderId: '129633734813',
    projectId: 'flutter-starter-49185',
    storageBucket: 'flutter-starter-49185.appspot.com',
    iosBundleId: 'com.example.firebaseexample.RunnerTests',
  );
}
